
universe = vanilla
log = log/gene_human.log
error = error/gene_human-chtc_$(Cluster)_$(Process).err

executable = ./gene_human.sh

arguments = LDLR_human.txt  $(Process)
output = output/gene_human-chtc_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R361.tar.gz, packages.tar.gz, gene_human.R, LDLR_human.txt,liver_human$INT(Process).txt


request_cpus = 1
request_memory = 30GB
request_disk = 10GB

queue 10 
