universe = vanilla
log = log/readData.log
error = error/readData-chtc_$(Cluster)_$(Process).err

executable = ./readData.sh

arguments = $(proc)
output = output/readData-chtc_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R361.tar.gz, packages.tar.gz, readData.R, download, download.1 


request_cpus = 1
request_memory = 60GB
request_disk = 12GB
 
queue 1
